### ISSUE TITLE
QUERY_TP and precision calculations

### ISSUE THREAD

**Issue by sq101** [TimD1/vcfdist#26] opened 2024-04-19 04:53 UTC
Hi there! We are currently using vcfdist for comparing variant callers. Our true set consists of 54 SNPs and 3 InDels (all of them homozygous). They seem to be picked up correctly as seen in the commands below

`tail -n +2 sample.resultstruth.tsv | awk -F "\t" '{if ($3 > 0) print $0}' | wc -l # Awk used to only consider one haplotype`
`57`

`tail -n +2 sample.resultstruth.tsv | awk -F "\t" '{if ($3 > 0) print $0}' | cut -f 8 | sort | uniq -c`
`57 TP`

This seems very positive indeed! Nonetheless, I am afraid I might not be interpreting the "resultsprecision-recall-summary.tsv" file correctly. Thus, I wanted to ask if you could help me clearing some points out.

The "resultsprecision-recall-summary.tsv" shows the following output:

![image](https://github.com/TimD1/vcfdist/assets/136267469/ea14b259-7d62-4350-a179-c160c21ead93)

I understand that homozygous alleles are split into 2 haplotypes, thus TRUTH_TP of 108 SNPs accounts for the 54 SNPs in the true set (54*2 =108). I am also aware that QUERY is used to calculate precision; however, for most variant callers that we have tested the number of variants found for TRUTH_TP and QUERY_TP are equal or very similar. Nonetheless, for the table above where FreeBayes variant caller was used, they seem to differ. **Thus I would like to kindly ask:**

(1) Is this an expected behaviour? How should this be interpreted and/or are there any implications on precision/recalling calculations?
(2) How should the QUERY_TP be interpreted? Could this be further elaborated?

Thank you very much for any reply and support and also for this very useful tool!!
Cheers,

**Comment by TimD1** [comment] 2024-04-19 13:54
Could you share the output `summary.vcf` file? That will contain a detailed breakdown of the truth and query variants necessary to answer your questions.

**Comment by TimD1** [comment] 2024-04-25 13:42
Followed up by email, closing here:

1a) Yes, this is expected behaviour. TRUTH_TP and QUERY_TP can differ because a complex true positive variant may not be represented the same in both the truth and query VCFs. Here's an example:

Query VCF
POS REF ALT
3      T       C
4      T       C
5      T       C

Truth VCF
POS  REF    ALT
2        A        ACCC
2        ATTT  A

This will result in TRUTH_TP = 2 (both INDELs) and QUERY_TP = 3 (all SNPs).

1b) Precision and recall are calculated as follows ([here](https://github.com/TimD1/vcfdist/blob/master/src/print.cpp#L467)):
PRECISION = QUERY_TP / (QUERY_TP + QUERY_FP)
RECALL = TRUTH_TP / (TRUTH_TP + TRUTH_FN)

2) It's the total count of true positive variants, using the variant representation from the query VCF.

**Closed by TimD1** 2024-04-25 13:42 UTC
